---
#    _    _   _       _                                   _      _____                 _    
#   | |  | | (_)     | |              /\                 | |    / ____|               | |   
#   | |__| |  _    __| |   ___       /  \     _ __     __| |   | (___     ___    ___  | | __
#   |  __  | | |  / _` |  / _ \     / /\ \   | '_ \   / _` |    \___ \   / _ \  / _ \ | |/ /
#   | |  | | | | | (_| | |  __/    / ____ \  | | | | | (_| |    ____) | |  __/ |  __/ |   < 
#   |_|  |_| |_|  \__,_|  \___|   /_/    \_\ |_| |_|  \__,_|   |_____/   \___|  \___| |_|\_\
#                                                                                           
#                                                                                           
# The original minigame, free, and better than ever !
# @author Ad5001
# @link ad5001.eu

# Welcome to HideAndSeek config.

# Parameters below are defaul parameters when not configured per world. 
# You can change them per world using in game commands
# Maximum amount of players per game. The game automaticly starts after 75% of the players have joined 
Max players: 16

# Seconds to wait between the time 75% of the maximum players have joined and the games starts.
Waiting time: 60

# Minutes seekers will have to find to find all the hiders before they win.
Seeking time: 3

# Percentage of the players that will be seekers.
Seekers percentage: 10



# Parameters below are set for every game and are not changable by commands
# The world players should be tped to when the game ends.
Lobby world: world

# Command, use {player} to change it into the selected player username !
# This is the command to be executed as console for all the players that won (original seekers if seekers wins / hiders left if hiders wins)
Winners command: give {player} diamond 1

# This is the command that will be executed for all the people that have lost (seekers if they lost / seekers that were hiders)
Losers command: give {player} dirt 64

# This will be executed for hiders that have been caught if seekers wins.
Semi winners command: give {player} iron_ingot
...